### ISSUE TITLE
Stable Version 4.0.0 Proposal

### ISSUE THREAD

**Issue by ClasherKasten** [DirectiveAthena/AthenaColor#4]
In this Issue we could collect all tasks necessary for getting to Version 4.0.0. In my opinion this should be then a stable version with no breaking changes (When breaking changes are necessary, then the version should get to 5.0.0 and so on).

My proposals would be:
- [x] More following the [PEP8](https://peps.python.org/pep-0008/) style guide
- [x] #9 
- [x] #6
- [x] Eventually some cleanup in other ways
- [x] #5

**Comment by AnnaSasDev** [comment]
The proposal to get to a stable 4.0.0 version is indeed something I was working to myself, and the version naming you proposed was something I already tried to adhere to. That said, I do admit to sometimes breaking or changing elements.

On your other proposals:

---
> More following the [PEP8](https://peps.python.org/pep-0008/) style guide

It's a style *guide* I often love and hate at the same time. I adhere to it when logical, but (like my `from x import (...)` ) I steer clear of it for either, better in code documentation, or ease of use. I don't really agree with this proposal

---
> adding unittests

Wouldn't see why this couldn't be implemented. A very good idea

---
> Implementing multiple color systems (not only tuples with no context) and the conversion between them

I was already working on this, as with the last 3.1.1 release there were conversion functions defined.

---
> Eventually some cleanup in other ways

Cleanup is something I do constantly, so absolutely agree

---
> Proper documentation (a library interface should be documented properly not only via some examples)

Absolutely! I just haven't gotten around to taking the time to write this

**Comment by AnnaSasDev** [comment]
Created the [4.0.0 Proposal Branch](https://github.com/DirectiveAthena/VerSC-AthenaColor/tree/4.0.0_Proposal)

**Comment by AnnaSasDev** [comment]
Created a rule on the master Branch to now only accept branch merges.
Will restrict me from "randomly" pushing things to the master branch without first debugging everything

**Comment by AnnaSasDev** [comment]
All color systems have now been implemented in the proposal branch with [this commit](https://github.com/DirectiveAthena/VerSC-AthenaColor/commit/6d5a010f9aeee91a4ce55f64c2f76da94eb75f72) 
Needs some verification
